### ISSUE TITLE
Public updatable domains list 

### ISSUE THREAD

**Issue by yetithefoot** [devondragon/10MinuteMailPublic#19]
Hello,

Thanks for the 10minutemail.com, very useful.
Is there a way to fetch the domains list, would be cool to integrate it into https://github.com/wesbos/burner-email-providers list.

**Comment by devondragon** [comment]
There is no API or anything like that which exposes the current domain list...  And while I do understand your concerns, I'm also not sure that making it easier to get the current domain list benefits me or my users in any fashion, so I don't think it's a feature I'm likely to add I guess...  It's too easy for sites to use your list as a blacklist rather than a "treat differently for bounce reduction goals"...

**Comment by yetithefoot** [comment]
Just trying to make a straight way to keep it fresh.
Anyway, thanks.
